---
- name: creating VPC1
  ec2_vpc_net:
    name: "{{ vpc_tag }}"
    cidr_block: "{{ cidr_block }}"
    region: us-west-2
    tags:
      module: ec2_vpc_net
      env: "{{ vpc_tag }}"
  register: myvpc

- name: creating public subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ myvpc.vpc.id }}"
    cidr: "{{ cidr_public_subnet }}"
    region: us-west-2
    az: us-west-2a
    resource_tags:
      Name: websubnet
      env: "{{ vpc_tag }}"
  register: web_subnet

- name: creating private subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ myvpc.vpc.id }}"
    cidr: "{{ cidr_private_subnet }}"
    region: us-west-2
    az: us-west-2b
    resource_tags:
      Name: dbsubnet
      env: "{{ vpc_tag }}"
  register: db_subnet

- debug:
   var: web_subnet

- debug:
   var: db_subnet

- name: creating internet gateway
  ec2_vpc_igw:
    vpc_id: "{{ myvpc.vpc.id }}"
    state: present
    region: us-west-2
    tags:
      Name: gateway
      env: "{{ vpc_tag }}"
  register: igw

- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ myvpc.vpc.id }}"
    region: us-west-2
    tags:
      Name: Public route table
      env: "{{ vpc_tag }}"
    subnets:
      - "{{ cidr_public_subnet }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
      - dest: "{{ cidr_block }}"
        vpc_id: "{{ myvpc.vpc.id }}"
  register: public_route_table

- name: Set up private subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ myvpc.vpc.id }}"
    region: us-west-2
    tags:
      Name: Private route table
      env: "{{ vpc_tag }}"
    subnets:
      - "{{ cidr_private_subnet }}"
    routes:
      - dest: "{{ cidr_block }}"
        vpc_id: "{{ myvpc.vpc.id }}"
  register: private_route_table

- name: security group for webserver
  ec2_group:
    name: websg
    description: security group for webserver
    vpc_id: "{{ myvpc.vpc.id }}"
    region: us-west-2
    tags:
      Name: websg
      env: "{{ vpc_tag }}"
    rules:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
  register: web_sg
- debug:
    var: web_sg

- name: security group for dbserver
  ec2_group:
    name: dbsg
    description: security group for dbserver
    vpc_id: "{{ myvpc.vpc.id }}"
    region: us-west-2
    tags:
      Name: dbsg
      env: "{{ vpc_tag }}"
    rules:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
  register: db_sg


#- name: security group for webserver
#  ec2_group:
#    name: websg
#    description: security group for webserver
#    vpc_id: "{{ myvpc.vpc.id }}"
#    region: us-west-2
#    tags:
#      Name: websg
#      env: "{{ vpc_tag }}"
#    rules:
#      - proto: tcp
#        ports:
#          - 80
#          - 443
#          - 22
#        cidr_ip: 0.0.0.0/0
#    rules_egress:
#      - proto: tcp
#        ports:
#          - 80
#          - 443
#          - 22
#        cidr_ip: 0.0.0.0/0
#      - proto: tcp
#        from_port: 3306
#        to_port: 3306
#        group_id: "{{ db_sg.group_id }}"

#- name: security group for dbserver
#  ec2_group:
#   name: dbsg
#    description: security group for dbserver
#    vpc_id: "{{ myvpc.vpc.id }}"
#    region: us-west-2
#    tags:
#      Name: dbsg
#      env: "{{ vpc_tag }}"
#    rules:
#      - proto: tcp
#        from_port: 22
#        to_port: 22
#        cidr_ip:  0.0.0.0/0
#      - proto: tcp
#        from_port: 3306
#        to_port: 3306
#        group_id: "{{ web_sg.group_id }}"
#    rules_egress:
#      - proto: tcp
#        from_port: 80
#        to_port: 80
#        cidr_ip:  0.0.0.0/0
#      - proto: tcp
#        from_port: 443
#        to_port: 443
#        cidr_ip:  0.0.0.0/0
#      - proto: tcp
#        from_port: 22
#        to_port: 22
#        vpc_id: "{{ myvpc.vpc.id }}"
#  register: db_sg
- debug:
    var: db_sg

